# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
- release/*

pool:
  vmImage: ubuntu-latest

steps:
- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: 'BassLines.Web'
    customCommand: 'install -g yarn'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      cd ./BassLines.Web
      yarn install
      yarn prod:webpack
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '6.x'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'dotnet publish ./BassLines.Api/BassLines.Api.csproj -c Release'
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: './BassLines.Api/bin/Release/net6.0/publish'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'drop'