trigger:
 branches:
  include:
    - main
    - release/*
 paths:
  include:
    - BassLines.Web/*

pool:
  vmImage: ubuntu-latest

steps:
- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: 'BassLines.Web'
    customCommand: 'install -g yarn'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      cd ./BassLines.Web
      yarn install
      yarn prod:webpack
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: './BassLines.Web/dist'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'drop'