/* tslint:disable */
/* eslint-disable */
/**
 * ChaggarCharts
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    LikeModel,
    LikeModelFromJSON,
    LikeModelToJSON,
} from '../models';

export interface LikesDeleteRequest {
    likeModel?: LikeModel;
}

export interface LikesPostRequest {
    likeModel?: LikeModel;
}

/**
 * 
 */
export class LikesApi extends runtime.BaseAPI {

    /**
     */
    async likesDeleteRaw(requestParameters: LikesDeleteRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/Likes`,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
            body: LikeModelToJSON(requestParameters.likeModel),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async likesDelete(requestParameters: LikesDeleteRequest, initOverrides?: RequestInit): Promise<void> {
        await this.likesDeleteRaw(requestParameters, initOverrides);
    }

    /**
     */
    async likesPostRaw(requestParameters: LikesPostRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/Likes`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LikeModelToJSON(requestParameters.likeModel),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async likesPost(requestParameters: LikesPostRequest, initOverrides?: RequestInit): Promise<void> {
        await this.likesPostRaw(requestParameters, initOverrides);
    }

}
