/* tslint:disable */
/* eslint-disable */
/**
 * ChaggarCharts
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    ModelValidationState,
    ModelValidationStateFromJSON,
    ModelValidationStateToJSON,
    SongModel,
    SongModelFromJSON,
    SongModelToJSON,
} from '../models';

export interface SongsPostRequest {
    songModel?: SongModel;
}

export interface SongsPutRequest {
    songModel?: SongModel;
}

export interface SongsSongSearchGetRequest {
    search?: string;
}

export interface SongsSubmissionDateSubmitDateStringGetRequest {
    submitDateString: string;
}

/**
 * 
 */
export class SongsApi extends runtime.BaseAPI {

    /**
     */
    async songsGetRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<SongModel>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/Songs`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(SongModelFromJSON));
    }

    /**
     */
    async songsGet(initOverrides?: RequestInit): Promise<Array<SongModel>> {
        const response = await this.songsGetRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async songsPostRaw(requestParameters: SongsPostRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<SongModel>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/Songs`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SongModelToJSON(requestParameters.songModel),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SongModelFromJSON(jsonValue));
    }

    /**
     */
    async songsPost(requestParameters: SongsPostRequest, initOverrides?: RequestInit): Promise<SongModel> {
        const response = await this.songsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async songsPutRaw(requestParameters: SongsPutRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<SongModel>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/Songs`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: SongModelToJSON(requestParameters.songModel),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SongModelFromJSON(jsonValue));
    }

    /**
     */
    async songsPut(requestParameters: SongsPutRequest, initOverrides?: RequestInit): Promise<SongModel> {
        const response = await this.songsPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async songsSongSearchGetRaw(requestParameters: SongsSongSearchGetRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<SongModel>>> {
        const queryParameters: any = {};

        if (requestParameters.search !== undefined) {
            queryParameters['search'] = requestParameters.search;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/Songs/SongSearch`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(SongModelFromJSON));
    }

    /**
     */
    async songsSongSearchGet(requestParameters: SongsSongSearchGetRequest, initOverrides?: RequestInit): Promise<Array<SongModel>> {
        const response = await this.songsSongSearchGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async songsSubmissionDateSubmitDateStringGetRaw(requestParameters: SongsSubmissionDateSubmitDateStringGetRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<SongModel>>> {
        if (requestParameters.submitDateString === null || requestParameters.submitDateString === undefined) {
            throw new runtime.RequiredError('submitDateString','Required parameter requestParameters.submitDateString was null or undefined when calling songsSubmissionDateSubmitDateStringGet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/Songs/SubmissionDate/{submitDateString}`.replace(`{${"submitDateString"}}`, encodeURIComponent(String(requestParameters.submitDateString))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(SongModelFromJSON));
    }

    /**
     */
    async songsSubmissionDateSubmitDateStringGet(requestParameters: SongsSubmissionDateSubmitDateStringGetRequest, initOverrides?: RequestInit): Promise<Array<SongModel>> {
        const response = await this.songsSubmissionDateSubmitDateStringGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
