/* tslint:disable */
/* eslint-disable */
/**
 * BassLines
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddTracksToPlaylistRequest
 */
export interface AddTracksToPlaylistRequest {
    /**
     * 
     * @type {string}
     * @memberof AddTracksToPlaylistRequest
     */
    id?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof AddTracksToPlaylistRequest
     */
    trackUris?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof AddTracksToPlaylistRequest
     */
    userId?: string | null;
}

export function AddTracksToPlaylistRequestFromJSON(json: any): AddTracksToPlaylistRequest {
    return AddTracksToPlaylistRequestFromJSONTyped(json, false);
}

export function AddTracksToPlaylistRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddTracksToPlaylistRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'trackUris': !exists(json, 'trackUris') ? undefined : json['trackUris'],
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
    };
}

export function AddTracksToPlaylistRequestToJSON(value?: AddTracksToPlaylistRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'trackUris': value.trackUris,
        'userId': value.userId,
    };
}

