/* tslint:disable */
/* eslint-disable */
/**
 * BassLines
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Artist,
    ArtistFromJSON,
    ArtistFromJSONTyped,
    ArtistToJSON,
} from './Artist';
import {
    ExternalUrls,
    ExternalUrlsFromJSON,
    ExternalUrlsFromJSONTyped,
    ExternalUrlsToJSON,
} from './ExternalUrls';
import {
    Image,
    ImageFromJSON,
    ImageFromJSONTyped,
    ImageToJSON,
} from './Image';

/**
 * 
 * @export
 * @interface AlbumRoot
 */
export interface AlbumRoot {
    /**
     * 
     * @type {string}
     * @memberof AlbumRoot
     */
    id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AlbumRoot
     */
    href?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AlbumRoot
     */
    uri?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AlbumRoot
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AlbumRoot
     */
    albumType?: string | null;
    /**
     * 
     * @type {Array<Artist>}
     * @memberof AlbumRoot
     */
    artists?: Array<Artist> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof AlbumRoot
     */
    availableMarkets?: Array<string> | null;
    /**
     * 
     * @type {ExternalUrls}
     * @memberof AlbumRoot
     */
    externalUrls?: ExternalUrls;
    /**
     * 
     * @type {Array<Image>}
     * @memberof AlbumRoot
     */
    images?: Array<Image> | null;
    /**
     * 
     * @type {string}
     * @memberof AlbumRoot
     */
    releaseDate?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AlbumRoot
     */
    releaseDatePrecision?: string | null;
    /**
     * 
     * @type {number}
     * @memberof AlbumRoot
     */
    totalTracks?: number | null;
    /**
     * 
     * @type {string}
     * @memberof AlbumRoot
     */
    type?: string | null;
}

export function AlbumRootFromJSON(json: any): AlbumRoot {
    return AlbumRootFromJSONTyped(json, false);
}

export function AlbumRootFromJSONTyped(json: any, ignoreDiscriminator: boolean): AlbumRoot {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'href': !exists(json, 'href') ? undefined : json['href'],
        'uri': !exists(json, 'uri') ? undefined : json['uri'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'albumType': !exists(json, 'album_type') ? undefined : json['album_type'],
        'artists': !exists(json, 'artists') ? undefined : (json['artists'] === null ? null : (json['artists'] as Array<any>).map(ArtistFromJSON)),
        'availableMarkets': !exists(json, 'available_markets') ? undefined : json['available_markets'],
        'externalUrls': !exists(json, 'external_urls') ? undefined : ExternalUrlsFromJSON(json['external_urls']),
        'images': !exists(json, 'images') ? undefined : (json['images'] === null ? null : (json['images'] as Array<any>).map(ImageFromJSON)),
        'releaseDate': !exists(json, 'release_date') ? undefined : json['release_date'],
        'releaseDatePrecision': !exists(json, 'release_date_precision') ? undefined : json['release_date_precision'],
        'totalTracks': !exists(json, 'total_tracks') ? undefined : json['total_tracks'],
        'type': !exists(json, 'type') ? undefined : json['type'],
    };
}

export function AlbumRootToJSON(value?: AlbumRoot | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'href': value.href,
        'uri': value.uri,
        'name': value.name,
        'album_type': value.albumType,
        'artists': value.artists === undefined ? undefined : (value.artists === null ? null : (value.artists as Array<any>).map(ArtistToJSON)),
        'available_markets': value.availableMarkets,
        'external_urls': ExternalUrlsToJSON(value.externalUrls),
        'images': value.images === undefined ? undefined : (value.images === null ? null : (value.images as Array<any>).map(ImageToJSON)),
        'release_date': value.releaseDate,
        'release_date_precision': value.releaseDatePrecision,
        'total_tracks': value.totalTracks,
        'type': value.type,
    };
}

