/* tslint:disable */
/* eslint-disable */
/**
 * BassLines
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ExternalUrls,
    ExternalUrlsFromJSON,
    ExternalUrlsFromJSONTyped,
    ExternalUrlsToJSON,
} from './ExternalUrls';

/**
 * 
 * @export
 * @interface Artist
 */
export interface Artist {
    /**
     * 
     * @type {string}
     * @memberof Artist
     */
    id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Artist
     */
    href?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Artist
     */
    uri?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Artist
     */
    name?: string | null;
    /**
     * 
     * @type {ExternalUrls}
     * @memberof Artist
     */
    externalUrls?: ExternalUrls;
    /**
     * 
     * @type {string}
     * @memberof Artist
     */
    type?: string | null;
}

export function ArtistFromJSON(json: any): Artist {
    return ArtistFromJSONTyped(json, false);
}

export function ArtistFromJSONTyped(json: any, ignoreDiscriminator: boolean): Artist {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'href': !exists(json, 'href') ? undefined : json['href'],
        'uri': !exists(json, 'uri') ? undefined : json['uri'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'externalUrls': !exists(json, 'external_urls') ? undefined : ExternalUrlsFromJSON(json['external_urls']),
        'type': !exists(json, 'type') ? undefined : json['type'],
    };
}

export function ArtistToJSON(value?: Artist | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'href': value.href,
        'uri': value.uri,
        'name': value.name,
        'external_urls': ExternalUrlsToJSON(value.externalUrls),
        'type': value.type,
    };
}

