/* tslint:disable */
/* eslint-disable */
/**
 * BassLines
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ExternalUrls,
    ExternalUrlsFromJSON,
    ExternalUrlsFromJSONTyped,
    ExternalUrlsToJSON,
} from './ExternalUrls';
import {
    Followers,
    FollowersFromJSON,
    FollowersFromJSONTyped,
    FollowersToJSON,
} from './Followers';
import {
    Image,
    ImageFromJSON,
    ImageFromJSONTyped,
    ImageToJSON,
} from './Image';

/**
 * 
 * @export
 * @interface ArtistDetails
 */
export interface ArtistDetails {
    /**
     * 
     * @type {string}
     * @memberof ArtistDetails
     */
    id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ArtistDetails
     */
    href?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ArtistDetails
     */
    uri?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ArtistDetails
     */
    name?: string | null;
    /**
     * 
     * @type {ExternalUrls}
     * @memberof ArtistDetails
     */
    externalUrls?: ExternalUrls;
    /**
     * 
     * @type {string}
     * @memberof ArtistDetails
     */
    type?: string | null;
    /**
     * 
     * @type {Followers}
     * @memberof ArtistDetails
     */
    followers?: Followers;
    /**
     * 
     * @type {Array<string>}
     * @memberof ArtistDetails
     */
    genres?: Array<string> | null;
    /**
     * 
     * @type {Array<Image>}
     * @memberof ArtistDetails
     */
    images?: Array<Image> | null;
    /**
     * 
     * @type {number}
     * @memberof ArtistDetails
     */
    popularity?: number | null;
}

export function ArtistDetailsFromJSON(json: any): ArtistDetails {
    return ArtistDetailsFromJSONTyped(json, false);
}

export function ArtistDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ArtistDetails {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'href': !exists(json, 'href') ? undefined : json['href'],
        'uri': !exists(json, 'uri') ? undefined : json['uri'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'externalUrls': !exists(json, 'external_urls') ? undefined : ExternalUrlsFromJSON(json['external_urls']),
        'type': !exists(json, 'type') ? undefined : json['type'],
        'followers': !exists(json, 'followers') ? undefined : FollowersFromJSON(json['followers']),
        'genres': !exists(json, 'genres') ? undefined : json['genres'],
        'images': !exists(json, 'images') ? undefined : (json['images'] === null ? null : (json['images'] as Array<any>).map(ImageFromJSON)),
        'popularity': !exists(json, 'popularity') ? undefined : json['popularity'],
    };
}

export function ArtistDetailsToJSON(value?: ArtistDetails | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'href': value.href,
        'uri': value.uri,
        'name': value.name,
        'external_urls': ExternalUrlsToJSON(value.externalUrls),
        'type': value.type,
        'followers': FollowersToJSON(value.followers),
        'genres': value.genres,
        'images': value.images === undefined ? undefined : (value.images === null ? null : (value.images as Array<any>).map(ImageToJSON)),
        'popularity': value.popularity,
    };
}

