/* tslint:disable */
/* eslint-disable */
/**
 * BassLines
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExternalUrls
 */
export interface ExternalUrls {
    /**
     * 
     * @type {string}
     * @memberof ExternalUrls
     */
    spotify?: string | null;
}

export function ExternalUrlsFromJSON(json: any): ExternalUrls {
    return ExternalUrlsFromJSONTyped(json, false);
}

export function ExternalUrlsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExternalUrls {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'spotify': !exists(json, 'spotify') ? undefined : json['spotify'],
    };
}

export function ExternalUrlsToJSON(value?: ExternalUrls | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'spotify': value.spotify,
    };
}

