/* tslint:disable */
/* eslint-disable */
/**
 * BassLines
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Followers
 */
export interface Followers {
    /**
     * 
     * @type {any}
     * @memberof Followers
     */
    href?: any | null;
    /**
     * 
     * @type {number}
     * @memberof Followers
     */
    total?: number | null;
}

export function FollowersFromJSON(json: any): Followers {
    return FollowersFromJSONTyped(json, false);
}

export function FollowersFromJSONTyped(json: any, ignoreDiscriminator: boolean): Followers {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'href': !exists(json, 'href') ? undefined : json['href'],
        'total': !exists(json, 'total') ? undefined : json['total'],
    };
}

export function FollowersToJSON(value?: Followers | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'href': value.href,
        'total': value.total,
    };
}

