/* tslint:disable */
/* eslint-disable */
/**
 * BassLines
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    UserModel,
    UserModelFromJSON,
    UserModelFromJSONTyped,
    UserModelToJSON,
} from './UserModel';

/**
 * 
 * @export
 * @interface LikeModel
 */
export interface LikeModel {
    /**
     * 
     * @type {string}
     * @memberof LikeModel
     */
    id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LikeModel
     */
    songId: string;
    /**
     * 
     * @type {string}
     * @memberof LikeModel
     */
    userId: string;
    /**
     * 
     * @type {UserModel}
     * @memberof LikeModel
     */
    user?: UserModel;
}

export function LikeModelFromJSON(json: any): LikeModel {
    return LikeModelFromJSONTyped(json, false);
}

export function LikeModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): LikeModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'songId': json['songId'],
        'userId': json['userId'],
        'user': !exists(json, 'user') ? undefined : UserModelFromJSON(json['user']),
    };
}

export function LikeModelToJSON(value?: LikeModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'songId': value.songId,
        'userId': value.userId,
        'user': UserModelToJSON(value.user),
    };
}

