/* tslint:disable */
/* eslint-disable */
/**
 * BassLines
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum ModelValidationState {
    Unvalidated = 'Unvalidated',
    Invalid = 'Invalid',
    Valid = 'Valid',
    Skipped = 'Skipped'
}

export function ModelValidationStateFromJSON(json: any): ModelValidationState {
    return ModelValidationStateFromJSONTyped(json, false);
}

export function ModelValidationStateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelValidationState {
    return json as ModelValidationState;
}

export function ModelValidationStateToJSON(value?: ModelValidationState | null): any {
    return value as any;
}

