/* tslint:disable */
/* eslint-disable */
/**
 * BassLines
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RemovePlaylistTrack
 */
export interface RemovePlaylistTrack {
    /**
     * 
     * @type {Array<string>}
     * @memberof RemovePlaylistTrack
     */
    uris?: Array<string> | null;
}

export function RemovePlaylistTrackFromJSON(json: any): RemovePlaylistTrack {
    return RemovePlaylistTrackFromJSONTyped(json, false);
}

export function RemovePlaylistTrackFromJSONTyped(json: any, ignoreDiscriminator: boolean): RemovePlaylistTrack {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'uris': !exists(json, 'uris') ? undefined : json['uris'],
    };
}

export function RemovePlaylistTrackToJSON(value?: RemovePlaylistTrack | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'uris': value.uris,
    };
}

