/* tslint:disable */
/* eslint-disable */
/**
 * BassLines
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Restrictions
 */
export interface Restrictions {
    /**
     * 
     * @type {string}
     * @memberof Restrictions
     */
    reason?: string | null;
}

export function RestrictionsFromJSON(json: any): Restrictions {
    return RestrictionsFromJSONTyped(json, false);
}

export function RestrictionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Restrictions {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'reason': !exists(json, 'reason') ? undefined : json['reason'],
    };
}

export function RestrictionsToJSON(value?: Restrictions | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'reason': value.reason,
    };
}

