/* tslint:disable */
/* eslint-disable */
/**
 * BassLines
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReviewerNotesModel
 */
export interface ReviewerNotesModel {
    /**
     * 
     * @type {string}
     * @memberof ReviewerNotesModel
     */
    notes?: string | null;
}

export function ReviewerNotesModelFromJSON(json: any): ReviewerNotesModel {
    return ReviewerNotesModelFromJSONTyped(json, false);
}

export function ReviewerNotesModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReviewerNotesModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'notes': !exists(json, 'notes') ? undefined : json['notes'],
    };
}

export function ReviewerNotesModelToJSON(value?: ReviewerNotesModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'notes': value.notes,
    };
}

