/* tslint:disable */
/* eslint-disable */
/**
 * BassLines
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    GenreModel,
    GenreModelFromJSON,
    GenreModelFromJSONTyped,
    GenreModelToJSON,
} from './GenreModel';
import {
    LikeModel,
    LikeModelFromJSON,
    LikeModelFromJSONTyped,
    LikeModelToJSON,
} from './LikeModel';
import {
    UserModel,
    UserModelFromJSON,
    UserModelFromJSONTyped,
    UserModelToJSON,
} from './UserModel';

/**
 * 
 * @export
 * @interface SongModel
 */
export interface SongModel {
    /**
     * 
     * @type {string}
     * @memberof SongModel
     */
    id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SongModel
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof SongModel
     */
    artist: string;
    /**
     * 
     * @type {GenreModel}
     * @memberof SongModel
     */
    genre?: GenreModel;
    /**
     * 
     * @type {UserModel}
     * @memberof SongModel
     */
    user?: UserModel;
    /**
     * 
     * @type {UserModel}
     * @memberof SongModel
     */
    reviewer?: UserModel;
    /**
     * 
     * @type {number}
     * @memberof SongModel
     */
    rating?: number | null;
    /**
     * 
     * @type {string}
     * @memberof SongModel
     */
    link?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof SongModel
     */
    submitteddate?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof SongModel
     */
    createdatetime?: Date | null;
    /**
     * 
     * @type {Array<LikeModel>}
     * @memberof SongModel
     */
    likes?: Array<LikeModel> | null;
}

export function SongModelFromJSON(json: any): SongModel {
    return SongModelFromJSONTyped(json, false);
}

export function SongModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): SongModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'title': json['title'],
        'artist': json['artist'],
        'genre': !exists(json, 'genre') ? undefined : GenreModelFromJSON(json['genre']),
        'user': !exists(json, 'user') ? undefined : UserModelFromJSON(json['user']),
        'reviewer': !exists(json, 'reviewer') ? undefined : UserModelFromJSON(json['reviewer']),
        'rating': !exists(json, 'rating') ? undefined : json['rating'],
        'link': !exists(json, 'link') ? undefined : json['link'],
        'submitteddate': !exists(json, 'submitteddate') ? undefined : (json['submitteddate'] === null ? null : new Date(json['submitteddate'])),
        'createdatetime': !exists(json, 'createdatetime') ? undefined : (json['createdatetime'] === null ? null : new Date(json['createdatetime'])),
        'likes': !exists(json, 'likes') ? undefined : (json['likes'] === null ? null : (json['likes'] as Array<any>).map(LikeModelFromJSON)),
    };
}

export function SongModelToJSON(value?: SongModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'title': value.title,
        'artist': value.artist,
        'genre': GenreModelToJSON(value.genre),
        'user': UserModelToJSON(value.user),
        'reviewer': UserModelToJSON(value.reviewer),
        'rating': value.rating,
        'link': value.link,
        'submitteddate': value.submitteddate === undefined ? undefined : (value.submitteddate === null ? null : value.submitteddate.toISOString()),
        'createdatetime': value.createdatetime === undefined ? undefined : (value.createdatetime === null ? null : value.createdatetime.toISOString()),
        'likes': value.likes === undefined ? undefined : (value.likes === null ? null : (value.likes as Array<any>).map(LikeModelToJSON)),
    };
}

