/* tslint:disable */
/* eslint-disable */
/**
 * BassLines
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    SpotifyPlaylist,
    SpotifyPlaylistFromJSON,
    SpotifyPlaylistFromJSONTyped,
    SpotifyPlaylistToJSON,
} from './SpotifyPlaylist';

/**
 * 
 * @export
 * @interface SpotifyPlaylistSearchRoot
 */
export interface SpotifyPlaylistSearchRoot {
    /**
     * 
     * @type {string}
     * @memberof SpotifyPlaylistSearchRoot
     */
    href?: string | null;
    /**
     * 
     * @type {Array<SpotifyPlaylist>}
     * @memberof SpotifyPlaylistSearchRoot
     */
    items?: Array<SpotifyPlaylist> | null;
    /**
     * 
     * @type {number}
     * @memberof SpotifyPlaylistSearchRoot
     */
    limit?: number | null;
    /**
     * 
     * @type {string}
     * @memberof SpotifyPlaylistSearchRoot
     */
    next?: string | null;
    /**
     * 
     * @type {number}
     * @memberof SpotifyPlaylistSearchRoot
     */
    offset?: number | null;
    /**
     * 
     * @type {any}
     * @memberof SpotifyPlaylistSearchRoot
     */
    previous?: any | null;
    /**
     * 
     * @type {number}
     * @memberof SpotifyPlaylistSearchRoot
     */
    total?: number | null;
}

export function SpotifyPlaylistSearchRootFromJSON(json: any): SpotifyPlaylistSearchRoot {
    return SpotifyPlaylistSearchRootFromJSONTyped(json, false);
}

export function SpotifyPlaylistSearchRootFromJSONTyped(json: any, ignoreDiscriminator: boolean): SpotifyPlaylistSearchRoot {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'href': !exists(json, 'href') ? undefined : json['href'],
        'items': !exists(json, 'items') ? undefined : (json['items'] === null ? null : (json['items'] as Array<any>).map(SpotifyPlaylistFromJSON)),
        'limit': !exists(json, 'limit') ? undefined : json['limit'],
        'next': !exists(json, 'next') ? undefined : json['next'],
        'offset': !exists(json, 'offset') ? undefined : json['offset'],
        'previous': !exists(json, 'previous') ? undefined : json['previous'],
        'total': !exists(json, 'total') ? undefined : json['total'],
    };
}

export function SpotifyPlaylistSearchRootToJSON(value?: SpotifyPlaylistSearchRoot | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'href': value.href,
        'items': value.items === undefined ? undefined : (value.items === null ? null : (value.items as Array<any>).map(SpotifyPlaylistToJSON)),
        'limit': value.limit,
        'next': value.next,
        'offset': value.offset,
        'previous': value.previous,
        'total': value.total,
    };
}

