/* tslint:disable */
/* eslint-disable */
/**
 * BassLines
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SpotifyArtist
 */
export interface SpotifyArtist {
    /**
     * 
     * @type {string}
     * @memberof SpotifyArtist
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SpotifyArtist
     */
    spotifyId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SpotifyArtist
     */
    link?: string | null;
}

export function SpotifyArtistFromJSON(json: any): SpotifyArtist {
    return SpotifyArtistFromJSONTyped(json, false);
}

export function SpotifyArtistFromJSONTyped(json: any, ignoreDiscriminator: boolean): SpotifyArtist {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'spotifyId': !exists(json, 'spotifyId') ? undefined : json['spotifyId'],
        'link': !exists(json, 'link') ? undefined : json['link'],
    };
}

export function SpotifyArtistToJSON(value?: SpotifyArtist | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'spotifyId': value.spotifyId,
        'link': value.link,
    };
}

