/* tslint:disable */
/* eslint-disable */
/**
 * BassLines
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SpotifyAlbumTrack
 */
export interface SpotifyAlbumTrack {
    /**
     * 
     * @type {string}
     * @memberof SpotifyAlbumTrack
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof SpotifyAlbumTrack
     */
    artist: string;
    /**
     * 
     * @type {string}
     * @memberof SpotifyAlbumTrack
     */
    link?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SpotifyAlbumTrack
     */
    spotifyId?: string | null;
    /**
     * 
     * @type {number}
     * @memberof SpotifyAlbumTrack
     */
    durationSeconds?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof SpotifyAlbumTrack
     */
    explicit?: boolean;
}

export function SpotifyAlbumTrackFromJSON(json: any): SpotifyAlbumTrack {
    return SpotifyAlbumTrackFromJSONTyped(json, false);
}

export function SpotifyAlbumTrackFromJSONTyped(json: any, ignoreDiscriminator: boolean): SpotifyAlbumTrack {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'title': json['title'],
        'artist': json['artist'],
        'link': !exists(json, 'link') ? undefined : json['link'],
        'spotifyId': !exists(json, 'spotifyId') ? undefined : json['spotifyId'],
        'durationSeconds': !exists(json, 'durationSeconds') ? undefined : json['durationSeconds'],
        'explicit': !exists(json, 'explicit') ? undefined : json['explicit'],
    };
}

export function SpotifyAlbumTrackToJSON(value?: SpotifyAlbumTrack | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': value.title,
        'artist': value.artist,
        'link': value.link,
        'spotifyId': value.spotifyId,
        'durationSeconds': value.durationSeconds,
        'explicit': value.explicit,
    };
}

