/* tslint:disable */
/* eslint-disable */
/**
 * BassLines
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Image,
    ImageFromJSON,
    ImageFromJSONTyped,
    ImageToJSON,
} from './Image';
import {
    SpotifyAlbumTrack,
    SpotifyAlbumTrackFromJSON,
    SpotifyAlbumTrackFromJSONTyped,
    SpotifyAlbumTrackToJSON,
} from './SpotifyAlbumTrack';
import {
    SpotifyBase,
    SpotifyBaseFromJSON,
    SpotifyBaseFromJSONTyped,
    SpotifyBaseToJSON,
} from './SpotifyBase';

/**
 * 
 * @export
 * @interface SpotifyAlbumDetails
 */
export interface SpotifyAlbumDetails {
    /**
     * 
     * @type {string}
     * @memberof SpotifyAlbumDetails
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SpotifyAlbumDetails
     */
    spotifyId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SpotifyAlbumDetails
     */
    link?: string | null;
    /**
     * 
     * @type {Array<Image>}
     * @memberof SpotifyAlbumDetails
     */
    images?: Array<Image> | null;
    /**
     * 
     * @type {SpotifyBase}
     * @memberof SpotifyAlbumDetails
     */
    artist?: SpotifyBase;
    /**
     * 
     * @type {Date}
     * @memberof SpotifyAlbumDetails
     */
    releaseDate?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof SpotifyAlbumDetails
     */
    trackCount?: number | null;
    /**
     * 
     * @type {Array<SpotifyAlbumTrack>}
     * @memberof SpotifyAlbumDetails
     */
    tracks?: Array<SpotifyAlbumTrack> | null;
}

export function SpotifyAlbumDetailsFromJSON(json: any): SpotifyAlbumDetails {
    return SpotifyAlbumDetailsFromJSONTyped(json, false);
}

export function SpotifyAlbumDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): SpotifyAlbumDetails {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'spotifyId': !exists(json, 'spotifyId') ? undefined : json['spotifyId'],
        'link': !exists(json, 'link') ? undefined : json['link'],
        'images': !exists(json, 'images') ? undefined : (json['images'] === null ? null : (json['images'] as Array<any>).map(ImageFromJSON)),
        'artist': !exists(json, 'artist') ? undefined : SpotifyBaseFromJSON(json['artist']),
        'releaseDate': !exists(json, 'releaseDate') ? undefined : (json['releaseDate'] === null ? null : new Date(json['releaseDate'])),
        'trackCount': !exists(json, 'trackCount') ? undefined : json['trackCount'],
        'tracks': !exists(json, 'tracks') ? undefined : (json['tracks'] === null ? null : (json['tracks'] as Array<any>).map(SpotifyAlbumTrackFromJSON)),
    };
}

export function SpotifyAlbumDetailsToJSON(value?: SpotifyAlbumDetails | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'spotifyId': value.spotifyId,
        'link': value.link,
        'images': value.images === undefined ? undefined : (value.images === null ? null : (value.images as Array<any>).map(ImageToJSON)),
        'artist': SpotifyBaseToJSON(value.artist),
        'releaseDate': value.releaseDate === undefined ? undefined : (value.releaseDate === null ? null : value.releaseDate.toISOString()),
        'trackCount': value.trackCount,
        'tracks': value.tracks === undefined ? undefined : (value.tracks === null ? null : (value.tracks as Array<any>).map(SpotifyAlbumTrackToJSON)),
    };
}

