/* tslint:disable */
/* eslint-disable */
/**
 * BassLines
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SpotifyLinkReference
 */
export interface SpotifyLinkReference {
    /**
     * 
     * @type {string}
     * @memberof SpotifyLinkReference
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof SpotifyLinkReference
     */
    artist: string;
    /**
     * 
     * @type {string}
     * @memberof SpotifyLinkReference
     */
    link?: string | null;
    /**
     * 
     * @type {number}
     * @memberof SpotifyLinkReference
     */
    rating?: number | null;
    /**
     * 
     * @type {Date}
     * @memberof SpotifyLinkReference
     */
    submitteddate?: Date | null;
}

export function SpotifyLinkReferenceFromJSON(json: any): SpotifyLinkReference {
    return SpotifyLinkReferenceFromJSONTyped(json, false);
}

export function SpotifyLinkReferenceFromJSONTyped(json: any, ignoreDiscriminator: boolean): SpotifyLinkReference {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'title': json['title'],
        'artist': json['artist'],
        'link': !exists(json, 'link') ? undefined : json['link'],
        'rating': !exists(json, 'rating') ? undefined : json['rating'],
        'submitteddate': !exists(json, 'submitteddate') ? undefined : (json['submitteddate'] === null ? null : new Date(json['submitteddate'])),
    };
}

export function SpotifyLinkReferenceToJSON(value?: SpotifyLinkReference | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': value.title,
        'artist': value.artist,
        'link': value.link,
        'rating': value.rating,
        'submitteddate': value.submitteddate === undefined ? undefined : (value.submitteddate === null ? null : value.submitteddate.toISOString()),
    };
}

