/* tslint:disable */
/* eslint-disable */
/**
 * BassLines
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SpotifyBase
 */
export interface SpotifyBase {
    /**
     * 
     * @type {string}
     * @memberof SpotifyBase
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SpotifyBase
     */
    spotifyId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SpotifyBase
     */
    link?: string | null;
}

export function SpotifyBaseFromJSON(json: any): SpotifyBase {
    return SpotifyBaseFromJSONTyped(json, false);
}

export function SpotifyBaseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SpotifyBase {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'spotifyId': !exists(json, 'spotifyId') ? undefined : json['spotifyId'],
        'link': !exists(json, 'link') ? undefined : json['link'],
    };
}

export function SpotifyBaseToJSON(value?: SpotifyBase | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'spotifyId': value.spotifyId,
        'link': value.link,
    };
}

