/* tslint:disable */
/* eslint-disable */
/**
 * BassLines
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Image,
    ImageFromJSON,
    ImageFromJSONTyped,
    ImageToJSON,
} from './Image';
import {
    SpotifyAlbum,
    SpotifyAlbumFromJSON,
    SpotifyAlbumFromJSONTyped,
    SpotifyAlbumToJSON,
} from './SpotifyAlbum';
import {
    SpotifyBase,
    SpotifyBaseFromJSON,
    SpotifyBaseFromJSONTyped,
    SpotifyBaseToJSON,
} from './SpotifyBase';

/**
 * 
 * @export
 * @interface SpotifyTrack
 */
export interface SpotifyTrack {
    /**
     * 
     * @type {string}
     * @memberof SpotifyTrack
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof SpotifyTrack
     */
    artist: string;
    /**
     * 
     * @type {string}
     * @memberof SpotifyTrack
     */
    link?: string | null;
    /**
     * 
     * @type {Array<Image>}
     * @memberof SpotifyTrack
     */
    images?: Array<Image> | null;
    /**
     * 
     * @type {number}
     * @memberof SpotifyTrack
     */
    durationSeconds?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof SpotifyTrack
     */
    explicit?: boolean | null;
    /**
     * 
     * @type {number}
     * @memberof SpotifyTrack
     */
    popularity?: number | null;
    /**
     * 
     * @type {string}
     * @memberof SpotifyTrack
     */
    spotifyId?: string | null;
    /**
     * 
     * @type {SpotifyBase}
     * @memberof SpotifyTrack
     */
    artistDetails?: SpotifyBase;
    /**
     * 
     * @type {SpotifyAlbum}
     * @memberof SpotifyTrack
     */
    album?: SpotifyAlbum;
}

export function SpotifyTrackFromJSON(json: any): SpotifyTrack {
    return SpotifyTrackFromJSONTyped(json, false);
}

export function SpotifyTrackFromJSONTyped(json: any, ignoreDiscriminator: boolean): SpotifyTrack {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'title': json['title'],
        'artist': json['artist'],
        'link': !exists(json, 'link') ? undefined : json['link'],
        'images': !exists(json, 'images') ? undefined : (json['images'] === null ? null : (json['images'] as Array<any>).map(ImageFromJSON)),
        'durationSeconds': !exists(json, 'durationSeconds') ? undefined : json['durationSeconds'],
        'explicit': !exists(json, 'explicit') ? undefined : json['explicit'],
        'popularity': !exists(json, 'popularity') ? undefined : json['popularity'],
        'spotifyId': !exists(json, 'spotifyId') ? undefined : json['spotifyId'],
        'artistDetails': !exists(json, 'artistDetails') ? undefined : SpotifyBaseFromJSON(json['artistDetails']),
        'album': !exists(json, 'album') ? undefined : SpotifyAlbumFromJSON(json['album']),
    };
}

export function SpotifyTrackToJSON(value?: SpotifyTrack | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': value.title,
        'artist': value.artist,
        'link': value.link,
        'images': value.images === undefined ? undefined : (value.images === null ? null : (value.images as Array<any>).map(ImageToJSON)),
        'durationSeconds': value.durationSeconds,
        'explicit': value.explicit,
        'popularity': value.popularity,
        'spotifyId': value.spotifyId,
        'artistDetails': SpotifyBaseToJSON(value.artistDetails),
        'album': SpotifyAlbumToJSON(value.album),
    };
}

