/* tslint:disable */
/* eslint-disable */
/**
 * BassLines
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Image,
    ImageFromJSON,
    ImageFromJSONTyped,
    ImageToJSON,
} from './Image';

/**
 * 
 * @export
 * @interface SpotifyArtistDetails
 */
export interface SpotifyArtistDetails {
    /**
     * 
     * @type {string}
     * @memberof SpotifyArtistDetails
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SpotifyArtistDetails
     */
    spotifyId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SpotifyArtistDetails
     */
    link?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof SpotifyArtistDetails
     */
    genres?: Array<string> | null;
    /**
     * 
     * @type {number}
     * @memberof SpotifyArtistDetails
     */
    popularity?: number | null;
    /**
     * 
     * @type {Array<Image>}
     * @memberof SpotifyArtistDetails
     */
    images?: Array<Image> | null;
    /**
     * 
     * @type {number}
     * @memberof SpotifyArtistDetails
     */
    followers?: number | null;
}

export function SpotifyArtistDetailsFromJSON(json: any): SpotifyArtistDetails {
    return SpotifyArtistDetailsFromJSONTyped(json, false);
}

export function SpotifyArtistDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): SpotifyArtistDetails {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'spotifyId': !exists(json, 'spotifyId') ? undefined : json['spotifyId'],
        'link': !exists(json, 'link') ? undefined : json['link'],
        'genres': !exists(json, 'genres') ? undefined : json['genres'],
        'popularity': !exists(json, 'popularity') ? undefined : json['popularity'],
        'images': !exists(json, 'images') ? undefined : (json['images'] === null ? null : (json['images'] as Array<any>).map(ImageFromJSON)),
        'followers': !exists(json, 'followers') ? undefined : json['followers'],
    };
}

export function SpotifyArtistDetailsToJSON(value?: SpotifyArtistDetails | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'spotifyId': value.spotifyId,
        'link': value.link,
        'genres': value.genres,
        'popularity': value.popularity,
        'images': value.images === undefined ? undefined : (value.images === null ? null : (value.images as Array<any>).map(ImageToJSON)),
        'followers': value.followers,
    };
}

