/* tslint:disable */
/* eslint-disable */
/**
 * BassLines
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StudioModel
 */
export interface StudioModel {
    /**
     * 
     * @type {string}
     * @memberof StudioModel
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof StudioModel
     */
    name?: string | null;
}

export function StudioModelFromJSON(json: any): StudioModel {
    return StudioModelFromJSONTyped(json, false);
}

export function StudioModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): StudioModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
    };
}

export function StudioModelToJSON(value?: StudioModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
    };
}

