/* tslint:disable */
/* eslint-disable */
/**
 * BassLines
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TrackSavedReference
 */
export interface TrackSavedReference {
    /**
     * 
     * @type {string}
     * @memberof TrackSavedReference
     */
    id?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof TrackSavedReference
     */
    saved?: boolean;
}

export function TrackSavedReferenceFromJSON(json: any): TrackSavedReference {
    return TrackSavedReferenceFromJSONTyped(json, false);
}

export function TrackSavedReferenceFromJSONTyped(json: any, ignoreDiscriminator: boolean): TrackSavedReference {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'saved': !exists(json, 'saved') ? undefined : json['saved'],
    };
}

export function TrackSavedReferenceToJSON(value?: TrackSavedReference | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'saved': value.saved,
    };
}

