/* tslint:disable */
/* eslint-disable */
/**
 * BassLines
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TrackListReference
 */
export interface TrackListReference {
    /**
     * 
     * @type {string}
     * @memberof TrackListReference
     */
    href?: string | null;
    /**
     * 
     * @type {number}
     * @memberof TrackListReference
     */
    total?: number;
}

export function TrackListReferenceFromJSON(json: any): TrackListReference {
    return TrackListReferenceFromJSONTyped(json, false);
}

export function TrackListReferenceFromJSONTyped(json: any, ignoreDiscriminator: boolean): TrackListReference {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'href': !exists(json, 'href') ? undefined : json['href'],
        'total': !exists(json, 'total') ? undefined : json['total'],
    };
}

export function TrackListReferenceToJSON(value?: TrackListReference | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'href': value.href,
        'total': value.total,
    };
}

