/* tslint:disable */
/* eslint-disable */
/**
 * BassLines
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TransferStateRequest
 */
export interface TransferStateRequest {
    /**
     * 
     * @type {Array<string>}
     * @memberof TransferStateRequest
     */
    deviceIds?: Array<string> | null;
}

export function TransferStateRequestFromJSON(json: any): TransferStateRequest {
    return TransferStateRequestFromJSONTyped(json, false);
}

export function TransferStateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransferStateRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'deviceIds': !exists(json, 'device_ids') ? undefined : json['device_ids'],
    };
}

export function TransferStateRequestToJSON(value?: TransferStateRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'device_ids': value.deviceIds,
    };
}

