/* tslint:disable */
/* eslint-disable */
/**
 * ChaggarCharts
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResetPasswordModel
 */
export interface ResetPasswordModel {
    /**
     * 
     * @type {string}
     * @memberof ResetPasswordModel
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof ResetPasswordModel
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof ResetPasswordModel
     */
    resetToken: string;
}

export function ResetPasswordModelFromJSON(json: any): ResetPasswordModel {
    return ResetPasswordModelFromJSONTyped(json, false);
}

export function ResetPasswordModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResetPasswordModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'username': json['username'],
        'password': json['password'],
        'resetToken': json['resetToken'],
    };
}

export function ResetPasswordModelToJSON(value?: ResetPasswordModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'username': value.username,
        'password': value.password,
        'resetToken': value.resetToken,
    };
}

