/* tslint:disable */
/* eslint-disable */
/**
 * BassLines
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    GenreModel,
    GenreModelFromJSON,
    GenreModelToJSON,
} from '../models';

/**
 * 
 */
export class GenresApi extends runtime.BaseAPI {

    /**
     */
    async apiGenresGetRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<GenreModel>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/Genres`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(GenreModelFromJSON));
    }

    /**
     */
    async apiGenresGet(initOverrides?: RequestInit): Promise<Array<GenreModel>> {
        const response = await this.apiGenresGetRaw(initOverrides);
        return await response.value();
    }

}
