/* tslint:disable */
/* eslint-disable */
/**
 * BassLines
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    ReviewerNotesModel,
    ReviewerNotesModelFromJSON,
    ReviewerNotesModelToJSON,
    UserModel,
    UserModelFromJSON,
    UserModelToJSON,
} from '../models';

export interface ApiReviewersNotesPutRequest {
    reviewerNotesModel?: ReviewerNotesModel;
}

export interface ApiReviewersRotateReviewerGetRequest {
    studioId?: string;
}

/**
 * 
 */
export class ReviewersApi extends runtime.BaseAPI {

    /**
     */
    async apiReviewersActiveGetRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<UserModel>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/Reviewers/Active`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserModelFromJSON(jsonValue));
    }

    /**
     */
    async apiReviewersActiveGet(initOverrides?: RequestInit): Promise<UserModel> {
        const response = await this.apiReviewersActiveGetRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async apiReviewersGetReviewerQueueGetRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<UserModel>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/Reviewers/GetReviewerQueue`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(UserModelFromJSON));
    }

    /**
     */
    async apiReviewersGetReviewerQueueGet(initOverrides?: RequestInit): Promise<Array<UserModel>> {
        const response = await this.apiReviewersGetReviewerQueueGetRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async apiReviewersNotesGetRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<string>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/Reviewers/Notes`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.TextApiResponse(response) as any;
    }

    /**
     */
    async apiReviewersNotesGet(initOverrides?: RequestInit): Promise<string> {
        const response = await this.apiReviewersNotesGetRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async apiReviewersNotesPutRaw(requestParameters: ApiReviewersNotesPutRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/Reviewers/Notes`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ReviewerNotesModelToJSON(requestParameters.reviewerNotesModel),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiReviewersNotesPut(requestParameters: ApiReviewersNotesPutRequest, initOverrides?: RequestInit): Promise<void> {
        await this.apiReviewersNotesPutRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiReviewersRebuildReviewerQueueGetRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/Reviewers/RebuildReviewerQueue`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiReviewersRebuildReviewerQueueGet(initOverrides?: RequestInit): Promise<void> {
        await this.apiReviewersRebuildReviewerQueueGetRaw(initOverrides);
    }

    /**
     */
    async apiReviewersRotateReviewerGetRaw(requestParameters: ApiReviewersRotateReviewerGetRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters.studioId !== undefined) {
            queryParameters['studioId'] = requestParameters.studioId;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/Reviewers/RotateReviewer`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiReviewersRotateReviewerGet(requestParameters: ApiReviewersRotateReviewerGetRequest, initOverrides?: RequestInit): Promise<void> {
        await this.apiReviewersRotateReviewerGetRaw(requestParameters, initOverrides);
    }

}
