/* tslint:disable */
/* eslint-disable */
/**
 * BassLines
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    MyDevices,
    MyDevicesFromJSON,
    MyDevicesToJSON,
    SongBaseWithImages,
    SongBaseWithImagesFromJSON,
    SongBaseWithImagesToJSON,
    SpotifyProfile,
    SpotifyProfileFromJSON,
    SpotifyProfileToJSON,
    SpotifyTrack,
    SpotifyTrackFromJSON,
    SpotifyTrackToJSON,
    SpotifyTrackDetails,
    SpotifyTrackDetailsFromJSON,
    SpotifyTrackDetailsToJSON,
    TransferStateRequest,
    TransferStateRequestFromJSON,
    TransferStateRequestToJSON,
} from '../models';

export interface AddToQueueSpotifyIdDeviceDeviceIdPutRequest {
    spotifyId: string;
    deviceId: string;
}

export interface ModelGetRequest {
    code?: string;
}

export interface PlaySpotifyIdDeviceDeviceIdPutRequest {
    spotifyId: string;
    deviceId: string;
}

export interface PlayerPutRequest {
    transferStateRequest?: TransferStateRequest;
}

export interface SearchGetRequest {
    query?: string;
}

export interface TrackIdDetailsGetRequest {
    id: string;
}

export interface TrackIdGetRequest {
    id: string;
}

/**
 * 
 */
export class SpotifyApi extends runtime.BaseAPI {

    /**
     */
    async addToQueueSpotifyIdDeviceDeviceIdPutRaw(requestParameters: AddToQueueSpotifyIdDeviceDeviceIdPutRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.spotifyId === null || requestParameters.spotifyId === undefined) {
            throw new runtime.RequiredError('spotifyId','Required parameter requestParameters.spotifyId was null or undefined when calling addToQueueSpotifyIdDeviceDeviceIdPut.');
        }

        if (requestParameters.deviceId === null || requestParameters.deviceId === undefined) {
            throw new runtime.RequiredError('deviceId','Required parameter requestParameters.deviceId was null or undefined when calling addToQueueSpotifyIdDeviceDeviceIdPut.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/add-to-queue/{spotifyId}/device/{deviceId}`.replace(`{${"spotifyId"}}`, encodeURIComponent(String(requestParameters.spotifyId))).replace(`{${"deviceId"}}`, encodeURIComponent(String(requestParameters.deviceId))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async addToQueueSpotifyIdDeviceDeviceIdPut(requestParameters: AddToQueueSpotifyIdDeviceDeviceIdPutRequest, initOverrides?: RequestInit): Promise<void> {
        await this.addToQueueSpotifyIdDeviceDeviceIdPutRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiSpotifyGetRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<string>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/Spotify`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.TextApiResponse(response) as any;
    }

    /**
     */
    async apiSpotifyGet(initOverrides?: RequestInit): Promise<string> {
        const response = await this.apiSpotifyGetRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async devicesGetRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<MyDevices>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/devices`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MyDevicesFromJSON(jsonValue));
    }

    /**
     */
    async devicesGet(initOverrides?: RequestInit): Promise<MyDevices> {
        const response = await this.devicesGetRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async meGetRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<SpotifyProfile>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/me`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SpotifyProfileFromJSON(jsonValue));
    }

    /**
     */
    async meGet(initOverrides?: RequestInit): Promise<SpotifyProfile> {
        const response = await this.meGetRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async modelGetRaw(requestParameters: ModelGetRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters.code !== undefined) {
            queryParameters['code'] = requestParameters.code;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/model`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async modelGet(requestParameters: ModelGetRequest, initOverrides?: RequestInit): Promise<void> {
        await this.modelGetRaw(requestParameters, initOverrides);
    }

    /**
     */
    async playSpotifyIdDeviceDeviceIdPutRaw(requestParameters: PlaySpotifyIdDeviceDeviceIdPutRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.spotifyId === null || requestParameters.spotifyId === undefined) {
            throw new runtime.RequiredError('spotifyId','Required parameter requestParameters.spotifyId was null or undefined when calling playSpotifyIdDeviceDeviceIdPut.');
        }

        if (requestParameters.deviceId === null || requestParameters.deviceId === undefined) {
            throw new runtime.RequiredError('deviceId','Required parameter requestParameters.deviceId was null or undefined when calling playSpotifyIdDeviceDeviceIdPut.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/play/{spotifyId}/device/{deviceId}`.replace(`{${"spotifyId"}}`, encodeURIComponent(String(requestParameters.spotifyId))).replace(`{${"deviceId"}}`, encodeURIComponent(String(requestParameters.deviceId))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async playSpotifyIdDeviceDeviceIdPut(requestParameters: PlaySpotifyIdDeviceDeviceIdPutRequest, initOverrides?: RequestInit): Promise<void> {
        await this.playSpotifyIdDeviceDeviceIdPutRaw(requestParameters, initOverrides);
    }

    /**
     */
    async playerPutRaw(requestParameters: PlayerPutRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/player`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: TransferStateRequestToJSON(requestParameters.transferStateRequest),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async playerPut(requestParameters: PlayerPutRequest, initOverrides?: RequestInit): Promise<void> {
        await this.playerPutRaw(requestParameters, initOverrides);
    }

    /**
     */
    async refreshGetRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/refresh`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async refreshGet(initOverrides?: RequestInit): Promise<void> {
        await this.refreshGetRaw(initOverrides);
    }

    /**
     */
    async searchGetRaw(requestParameters: SearchGetRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<SongBaseWithImages>>> {
        const queryParameters: any = {};

        if (requestParameters.query !== undefined) {
            queryParameters['query'] = requestParameters.query;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/search`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(SongBaseWithImagesFromJSON));
    }

    /**
     */
    async searchGet(requestParameters: SearchGetRequest, initOverrides?: RequestInit): Promise<Array<SongBaseWithImages>> {
        const response = await this.searchGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async trackIdDetailsGetRaw(requestParameters: TrackIdDetailsGetRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<SpotifyTrackDetails>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling trackIdDetailsGet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/track/{id}/details`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SpotifyTrackDetailsFromJSON(jsonValue));
    }

    /**
     */
    async trackIdDetailsGet(requestParameters: TrackIdDetailsGetRequest, initOverrides?: RequestInit): Promise<SpotifyTrackDetails> {
        const response = await this.trackIdDetailsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async trackIdGetRaw(requestParameters: TrackIdGetRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<SpotifyTrack>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling trackIdGet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/track/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SpotifyTrackFromJSON(jsonValue));
    }

    /**
     */
    async trackIdGet(requestParameters: TrackIdGetRequest, initOverrides?: RequestInit): Promise<SpotifyTrack> {
        const response = await this.trackIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
