name: Yarn Install, Run, and Zip

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14

    - name: Install Dependencies
      working-directory: ./BassLines.Web
      run: yarn install

    - name: Run Yarn Command
      working-directory: ./BassLines.Web
      run: yarn prod:webpack

    - name: Zip Directory
      working-directory: ./BassLines.Web/dist
      run: zip -r archive.zip ./

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: archive.zip
