name: Deploy to Remote Server

on:
  push:
    branches:
      - main
    tags:        
      - 'release/v**'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_type == 'tag' && startsWith(github.ref_name, 'release') && 'production' || 'development' }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14

    - name: Install Dependencies
      working-directory: ./BassLines.Web
      run: yarn install

    - name: Run Yarn Command
      working-directory: ./BassLines.Web
      run: yarn prod:webpack

    - name: Swap Environment Variables in JavaScript File
      run: |
        sed -i "s|__API_URL__|${{vars.API_URL}}|g" ./BassLines.Web/dist/configs.js

    - name: Zip Directory
      working-directory: ./BassLines.Web/dist
      run: zip -r basslines.web.${{github.run_number}}.zip ./

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: basslines.web.${{github.run_number}}
        path: ./BassLines.Web/dist/basslines.web.${{github.run_number}}.zip

  deploy_remote:
    needs: build
    runs-on: ubuntu-latest
    environment: ${{ github.ref_type == 'tag' && startsWith(github.ref_name, 'release') && 'production' || 'development' }}
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: basslines.web.${{github.run_number}}
          path: .

      - name: Create SSH Directory
        run: mkdir ~/.ssh && chmod 700 ~/.ssh

      - name: Create SSH File
        run: touch ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa

      - name: Install SSH Key
        run: echo "${{secrets.LIGHTSAIL_SSH_KEY}}" > ~/.ssh/id_rsa
        
      - name: Copy Artifact to Remote Server
        run: scp -o StrictHostKeyChecking=no -r basslines.web.${{github.run_number}}.zip ec2-user@alexanderdev.com:/appl/${{vars.DEPLOYMENT_DIRECTORY}}

      - name: Install Application Files
        run: ssh ec2-user@alexanderdev.com 'unzip -o /appl/${{vars.DEPLOYMENT_DIRECTORY}}/basslines.web.${{github.run_number}}.zip -d /appl/${{vars.DEPLOYMENT_DIRECTORY}}'
